/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalProject1;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import javax.swing.JPanel;

/**
 *
 * @author Xentos
 */
public class AboutUs extends javax.swing.JFrame {

    /**
     * Creates new form AboutUs
     */
    public AboutUs() {
        initComponents();
        Toolkit toolkit= getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2 );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblFirstName = new javax.swing.JLabel();
        lblFirstName1 = new javax.swing.JLabel();
        lblFirstName2 = new javax.swing.JLabel();
        lblFirstName4 = new javax.swing.JLabel();
        lblFirstName5 = new javax.swing.JLabel();
        lblFirstName6 = new javax.swing.JLabel();
        lblFirstName7 = new javax.swing.JLabel();
        lblFirstName8 = new javax.swing.JLabel();
        lblFirstName9 = new javax.swing.JLabel();
        lblFirstName10 = new javax.swing.JLabel();
        lblFirstName11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btnLogIn = new javax.swing.JButton();
        logo1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        lblFirstName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(153, 153, 153));
        lblFirstName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFirstName.setText("Birana is a Course File Management Software that is designed to facillitate the ");
        jPanel1.add(lblFirstName);
        lblFirstName.setBounds(270, 60, 570, 20);

        lblFirstName1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFirstName1.setForeground(new java.awt.Color(153, 153, 153));
        lblFirstName1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFirstName1.setText("lecturers  and Students. The Software aids students in getting access to course ");
        jPanel1.add(lblFirstName1);
        lblFirstName1.setBounds(270, 100, 560, 20);

        lblFirstName2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFirstName2.setForeground(new java.awt.Color(153, 153, 153));
        lblFirstName2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFirstName2.setText("they have registered for. ");
        jPanel1.add(lblFirstName2);
        lblFirstName2.setBounds(270, 140, 580, 20);

        lblFirstName4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFirstName4.setForeground(new java.awt.Color(153, 153, 153));
        lblFirstName4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFirstName4.setText("teaching learning experience by introducing a new way of file sharing between ");
        jPanel1.add(lblFirstName4);
        lblFirstName4.setBounds(270, 80, 600, 20);

        lblFirstName5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFirstName5.setForeground(new java.awt.Color(153, 153, 153));
        lblFirstName5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFirstName5.setText("file materials of their  choice and lets  students  save  filles for the courses that ");
        jPanel1.add(lblFirstName5);
        lblFirstName5.setBounds(270, 120, 590, 20);

        lblFirstName6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFirstName6.setForeground(new java.awt.Color(153, 153, 153));
        lblFirstName6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFirstName6.setText("DEVELOPED BY");
        jPanel1.add(lblFirstName6);
        lblFirstName6.setBounds(380, 400, 110, 30);

        lblFirstName7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFirstName7.setForeground(new java.awt.Color(153, 153, 153));
        lblFirstName7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFirstName7.setText("Dagmawi Mekonnen");
        jPanel1.add(lblFirstName7);
        lblFirstName7.setBounds(90, 440, 150, 30);

        lblFirstName8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFirstName8.setForeground(new java.awt.Color(153, 153, 153));
        lblFirstName8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFirstName8.setText("Elroe Tadele");
        jPanel1.add(lblFirstName8);
        lblFirstName8.setBounds(390, 440, 100, 30);

        lblFirstName9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFirstName9.setForeground(new java.awt.Color(153, 153, 153));
        lblFirstName9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFirstName9.setText("Ezana HaileSellassie");
        jPanel1.add(lblFirstName9);
        lblFirstName9.setBounds(500, 440, 150, 30);

        lblFirstName10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFirstName10.setForeground(new java.awt.Color(153, 153, 153));
        lblFirstName10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFirstName10.setText("Fitsum Mekonnen");
        jPanel1.add(lblFirstName10);
        lblFirstName10.setBounds(660, 440, 130, 30);

        lblFirstName11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFirstName11.setForeground(new java.awt.Color(153, 153, 153));
        lblFirstName11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFirstName11.setText("Daniel Deggebas");
        jPanel1.add(lblFirstName11);
        lblFirstName11.setBounds(250, 440, 130, 30);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(10, 470, 870, 20);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(10, 440, 870, 40);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(270, 50, 560, 30);

        btnLogIn.setText("BACK");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogIn);
        btnLogIn.setBounds(0, 0, 70, 30);

        logo1.setBackground(new java.awt.Color(255, 0, 0));
        logo1.setFont(new java.awt.Font("Starcruiser", 2, 36)); // NOI18N
        logo1.setForeground(new java.awt.Color(0, 0, 102));
        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalProject1/download (1).png"))); // NOI18N
        jPanel1.add(logo1);
        logo1.setBounds(-20, 20, 350, 210);

        jLabel14.setBackground(new java.awt.Color(255, 0, 0));
        jLabel14.setFont(new java.awt.Font("orange juice", 2, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 0, 0));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalProject1/bac4k.png"))); // NOI18N
        jLabel14.setText("BIRANA");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(0, 0, 890, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        if (SignUp1.us==1)
        {
        SignUp1.main(null);
        this.dispose();
        }
        else if (SignUp1.us==2)
        {
        StudentHomePage.main(null);
        this.dispose();
        }
         else if (SignUp1.us==3)
        {
        TeacherHomePage.main(null);
        this.dispose();
        }
        else if (SignUp1.us==4)
        {
        DatabaseLogin.main(null);
        this.dispose();
        }
        
        
    }//GEN-LAST:event_btnLogInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new AboutUs().setVisible(true);
                
            }
        });
    }
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogIn;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblFirstName1;
    private javax.swing.JLabel lblFirstName10;
    private javax.swing.JLabel lblFirstName11;
    private javax.swing.JLabel lblFirstName2;
    private javax.swing.JLabel lblFirstName4;
    private javax.swing.JLabel lblFirstName5;
    private javax.swing.JLabel lblFirstName6;
    private javax.swing.JLabel lblFirstName7;
    private javax.swing.JLabel lblFirstName8;
    private javax.swing.JLabel lblFirstName9;
    private javax.swing.JLabel logo1;
    // End of variables declaration//GEN-END:variables
}
