/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalProject1;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;
import javax.swing.*;

/**
 *
 * @author Tadele
 */
public class AddFile extends javax.swing.JFrame {

    /**
     * Creates new form AddFile
     */
    String un = Database.uname, up = Database.upass;
    static int id, cid;

    public AddFile() {
        initComponents();
        Toolkit toolkit= getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2 );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblData = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnBrowse = new javax.swing.JButton();
        lblFile = new javax.swing.JLabel();
        lblFileName = new javax.swing.JLabel();
        fileNameTextField = new javax.swing.JTextField();
        lblD = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        btnCancel.setText("CANCEL");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel);
        btnCancel.setBounds(251, 180, 80, 23);

        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd);
        btnAdd.setBounds(140, 180, 79, 23);

        btnBrowse.setText("Browse...");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });
        jPanel1.add(btnBrowse);
        btnBrowse.setBounds(140, 120, 80, 23);

        lblFile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFile.setForeground(new java.awt.Color(255, 255, 255));
        lblFile.setText("File:");
        jPanel1.add(lblFile);
        lblFile.setBounds(50, 120, 80, 17);

        lblFileName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFileName.setForeground(new java.awt.Color(255, 255, 255));
        lblFileName.setText("File Name:");
        jPanel1.add(lblFileName);
        lblFileName.setBounds(50, 90, 80, 26);
        jPanel1.add(fileNameTextField);
        fileNameTextField.setBounds(140, 90, 212, 26);
        jPanel1.add(lblD);
        lblD.setBounds(230, 120, 160, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalProject1/Space-PNG-HD.png"))); // NOI18N
        jLabel8.setText("jLabel7");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 400, 260);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(lblData, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblData)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:
        String fileName = fileNameTextField.getText();
        if (fileName.equals("")) {
            JOptionPane.showMessageDialog(null, "File Name cannot be empty");
        } else {
            JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
            int r = jfc.showOpenDialog(null);
            if (r == JFileChooser.APPROVE_OPTION) {
                Statement stat;
                ResultSet rs;
                String url;
                int len;
                String query;
                PreparedStatement pstmt;
                try {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    url = "jdbc:sqlserver://localhost:1433;databaseName=courseManagement";
                    Connection con = DriverManager.getConnection(url, un, up);
                    File file = new File(jfc.getSelectedFile().getAbsolutePath());
                    FileInputStream fis = new FileInputStream(file);
                    len = (int) file.length();
                    stat = con.createStatement();
                    String cmdtxt = "SELECT TID,TUName FROM TblTeacher WHERE TID=" + id;
                    rs = stat.executeQuery(cmdtxt);
                    rs.next();
                    String tuname = rs.getString(2);
                    query = "insert into Files values (?,?,?,?,?,?)";
                    //stat.execute(sqltxt);
                    pstmt = con.prepareStatement(query);
                    pstmt.setString(1, fileName);
                    pstmt.setString(2, jfc.getSelectedFile().getPath());
                    pstmt.setString(3, tuname);
                    pstmt.setDate(4, java.sql.Date.valueOf(java.time.LocalDate.now()));
                    pstmt.setBinaryStream(5, fis, len);
                    pstmt.setInt(6, cid);
                    pstmt.executeUpdate();
                    con.close();
                    lblD.setText(jfc.getSelectedFile().getAbsolutePath());

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                    //jl2.setText("ERROR!");
                }
            }
        }

    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if (fileNameTextField.getText().equals("") || lblD.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "File Name and/or File cannot be empty!");
        } else {
            JOptionPane.showMessageDialog(null, "ADDED!");
            String url;
            String un, up;
            un = Database.uname;
            up = Database.upass;
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                url = "jdbc:sqlserver://localhost:1433;databasename=courseManagement";
                Connection con = DriverManager.getConnection(url, un, up);
                Statement stat = con.createStatement();
                String cmdtxt = "SELECT CourseID, CourseName, Instructor FROM Courses WHERE CourseID=" + cid;
                ResultSet rs = stat.executeQuery(cmdtxt);
                rs.next();
                String cname = rs.getString(2);
                String tname = rs.getString(3);
                cmdtxt = "SELECT TblStudent.SID, TblStudent.SUName FROM TakesCourses "
                        + "JOIN TblStudent ON TakesCourses.SID=TblStudent.SID WHERE CourseID=" + cid;
                rs = stat.executeQuery(cmdtxt);
                while (rs.next()) {
                    Database.AddSNotification(rs.getInt(1), tname, "File Added to Course " + cname);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            this.dispose();
            OpenFileTeacher.main(null);
        }

    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnCancel;
    private javax.swing.JTextField fileNameTextField;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblD;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblFile;
    private javax.swing.JLabel lblFileName;
    // End of variables declaration//GEN-END:variables
}
