/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalProject1;

import java.awt.*;
import javax.swing.*;

public class DatabaseLogin extends javax.swing.JFrame {

    /**
     * Creates new form DatabaseLogin
     */
    public DatabaseLogin() {
        initComponents();
        Toolkit toolkit= getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2 );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGo = new javax.swing.JButton();
        passField = new javax.swing.JPasswordField();
        lblPassword = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        lblUsername1 = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        lblUsername2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        btnGo.setText("GO");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });
        jPanel1.add(btnGo);
        btnGo.setBounds(40, 180, 300, 30);
        jPanel1.add(passField);
        passField.setBounds(40, 140, 300, 25);

        lblPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password");
        jPanel1.add(lblPassword);
        lblPassword.setBounds(40, 110, 300, 25);

        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(153, 153, 153));
        lblUsername.setText("Please use your own Databse Authentication");
        jPanel1.add(lblUsername);
        lblUsername.setBounds(50, 210, 280, 25);
        jPanel1.add(usernameTextField);
        usernameTextField.setBounds(40, 80, 300, 25);

        lblUsername1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsername1.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername1.setText("Username");
        jPanel1.add(lblUsername1);
        lblUsername1.setBounds(40, 50, 300, 25);

        lblLogin.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setText("DATABASE LOGIN");
        jPanel1.add(lblLogin);
        lblLogin.setBounds(70, 10, 239, 28);

        lblUsername2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUsername2.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername2.setText("@2019 Birana");
        lblUsername2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsername2MouseClicked(evt);
            }
        });
        jPanel1.add(lblUsername2);
        lblUsername2.setBounds(150, 240, 90, 25);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalProject1/Space-PNG-HD.png"))); // NOI18N
        jLabel8.setText("jLabel7");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, -10, 370, 280);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        // TODO add your handling code here:
        uname=usernameTextField.getText();
        password=String.valueOf(passField.getPassword());
        this.dispose();
        Database d=new Database(uname,password);
        String s=d.createDB();
        s=d.createTables();
        if(s.equals(""))
        {
            LogIn1.main(null);
        }
        else
        {
            JOptionPane.showMessageDialog(null, s);
            //this.dispose();
        }
    }//GEN-LAST:event_btnGoActionPerformed

    private void lblUsername2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsername2MouseClicked
      this.dispose();
      AboutUs.main(null);
      SignUp1.us=4; 
    }//GEN-LAST:event_lblUsername2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatabaseLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatabaseLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatabaseLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatabaseLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatabaseLogin().setVisible(true);
            }
        });
    }
    
    String uname,password;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGo;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsername1;
    private javax.swing.JLabel lblUsername2;
    private javax.swing.JPasswordField passField;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
