package finalProject1;

import javax.swing.*;
import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import net.proteanit.sql.DbUtils;

public class LogIn1 extends javax.swing.JFrame {
    static String name, pass;
    public LogIn1() {
        initComponents();
        //String[] items={"Student","Teacher"};
            ComboBoxStudTeacher.addItem("-");
        ComboBoxStudTeacher.addItem("Student");
        ComboBoxStudTeacher.addItem("Teacher");  
        Toolkit toolkit= getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2 );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRequired = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblPassword = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        UserName_login = new javax.swing.JTextField();
        UserPassword_login = new javax.swing.JPasswordField();
        btnSignUp = new javax.swing.JButton();
        btnLogIn = new javax.swing.JButton();
        ComboBoxStudTeacher = new javax.swing.JComboBox<>();
        lblIAmA = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblPassword2 = new javax.swing.JLabel();
        lblUsername4 = new javax.swing.JLabel();
        usernameTextField4 = new javax.swing.JTextField();
        jPasswordField3 = new javax.swing.JPasswordField();
        usernameTextField5 = new javax.swing.JTextField();
        lblUsername5 = new javax.swing.JLabel();
        btnSignUp2 = new javax.swing.JButton();
        btnLogIn2 = new javax.swing.JButton();
        ComboBoxStudTeacher2 = new javax.swing.JComboBox<>();
        lblIAmA2 = new javax.swing.JLabel();
        btnLogIn1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));
        jPanel4.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(null);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("MANAGE YOUR COURSE FILES THE EASY WAY");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(300, 240, 330, 30);

        jLabel4.setBackground(new java.awt.Color(0, 0, 51));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalProject1/hh.PNG"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(280, 130, 360, 110);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        lblPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password");
        jPanel1.add(lblPassword);
        lblPassword.setBounds(20, 150, 231, 17);

        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username");
        jPanel1.add(lblUsername);
        lblUsername.setBounds(20, 80, 231, 17);

        UserName_login.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        UserName_login.setInheritsPopupMenu(true);
        jPanel1.add(UserName_login);
        UserName_login.setBounds(20, 110, 230, 30);

        UserPassword_login.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jPanel1.add(UserPassword_login);
        UserPassword_login.setBounds(20, 180, 231, 30);

        btnSignUp.setBackground(new java.awt.Color(0, 0, 51));
        btnSignUp.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUp.setText("Sign Up");
        btnSignUp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 51), new java.awt.Color(0, 0, 51), new java.awt.Color(0, 0, 51), new java.awt.Color(0, 0, 51)));
        btnSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        jPanel1.add(btnSignUp);
        btnSignUp.setBounds(380, 480, 57, 30);

        btnLogIn.setBackground(new java.awt.Color(0, 0, 51));
        btnLogIn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLogIn.setForeground(new java.awt.Color(255, 255, 255));
        btnLogIn.setText("Log In");
        btnLogIn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 51), new java.awt.Color(0, 0, 51)));
        btnLogIn.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogIn);
        btnLogIn.setBounds(20, 250, 231, 30);

        ComboBoxStudTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxStudTeacherActionPerformed(evt);
            }
        });
        jPanel1.add(ComboBoxStudTeacher);
        ComboBoxStudTeacher.setBounds(100, 310, 110, 30);

        lblIAmA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIAmA.setForeground(new java.awt.Color(255, 255, 255));
        lblIAmA.setText("Title");
        jPanel1.add(lblIAmA);
        lblIAmA.setBounds(50, 310, 50, 30);

        jPanel5.setBackground(new java.awt.Color(0, 0, 51));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setForeground(new java.awt.Color(102, 102, 102));
        jPanel5.setLayout(null);

        lblPassword2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPassword2.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword2.setText("Password");
        jPanel5.add(lblPassword2);
        lblPassword2.setBounds(13, 214, 231, 17);

        lblUsername4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsername4.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername4.setText("Username");
        jPanel5.add(lblUsername4);
        lblUsername4.setBounds(13, 152, 231, 17);

        usernameTextField4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        usernameTextField4.setInheritsPopupMenu(true);
        usernameTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextField4ActionPerformed(evt);
            }
        });
        jPanel5.add(usernameTextField4);
        usernameTextField4.setBounds(13, 175, 231, 24);

        jPasswordField3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jPasswordField3.setText("jPasswordField1");
        jPanel5.add(jPasswordField3);
        jPasswordField3.setBounds(13, 237, 231, 24);

        usernameTextField5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jPanel5.add(usernameTextField5);
        usernameTextField5.setBounds(13, 113, 231, 24);

        lblUsername5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsername5.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername5.setText("ID");
        jPanel5.add(lblUsername5);
        lblUsername5.setBounds(13, 90, 231, 17);

        btnSignUp2.setBackground(new java.awt.Color(0, 0, 51));
        btnSignUp2.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        btnSignUp2.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUp2.setText("Sign Up");
        btnSignUp2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 51), new java.awt.Color(0, 0, 51), new java.awt.Color(0, 0, 51), new java.awt.Color(0, 0, 51)));
        btnSignUp2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSignUp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUp2ActionPerformed(evt);
            }
        });
        jPanel5.add(btnSignUp2);
        btnSignUp2.setBounds(380, 480, 57, 30);

        btnLogIn2.setBackground(new java.awt.Color(0, 0, 51));
        btnLogIn2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLogIn2.setForeground(new java.awt.Color(255, 255, 255));
        btnLogIn2.setText("Log In");
        btnLogIn2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 51), new java.awt.Color(0, 0, 51)));
        btnLogIn2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnLogIn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogIn2ActionPerformed(evt);
            }
        });
        jPanel5.add(btnLogIn2);
        btnLogIn2.setBounds(13, 286, 231, 28);

        ComboBoxStudTeacher2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxStudTeacher2ActionPerformed(evt);
            }
        });
        jPanel5.add(ComboBoxStudTeacher2);
        ComboBoxStudTeacher2.setBounds(97, 332, 104, 22);

        lblIAmA2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblIAmA2.setForeground(new java.awt.Color(255, 255, 255));
        lblIAmA2.setText("I'm a");
        jPanel5.add(lblIAmA2);
        lblIAmA2.setBounds(65, 332, 30, 23);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(300, 410, 257, 390);

        btnLogIn1.setText("Sign Up");
        btnLogIn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogIn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogIn1);
        btnLogIn1.setBounds(170, 20, 80, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalProject1/Space-PNG-HD.png"))); // NOI18N
        jLabel8.setText("jLabel7");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 270, 380);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(647, 0, 270, 380);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("HiLCoE EDITION");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 0, 170, 20);

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 51));
        jLabel13.setText("V.0.1");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(10, 20, 50, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalProject1/BOOKS.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 660, 380);

        jPanel4.add(jPanel2);
        jPanel2.setBounds(0, 0, 920, 380);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(lblRequired, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(lblRequired))
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxStudTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxStudTeacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxStudTeacherActionPerformed

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        // TODO add your handling code here:
     Statement Stat;
     String URL;
     ResultSet RS_Authentication;
     int Flag=0;
     String UserNameLogin=UserName_login.getText();
     String UserPasswordLogin=UserPassword_login.getText();
     char[] input = UserPassword_login.getPassword();
     String Pass=String.valueOf(input) ;
     String un=Database.uname,up=Database.upass;
     
     if (UserNameLogin.isEmpty())
     {
           JOptionPane.showMessageDialog(null, "User Name Cannot be Empty");
     }
     else  if (UserPasswordLogin.isEmpty())
     {
           JOptionPane.showMessageDialog(null, "Password Cannot be Empty");
     }
       else  if  (ComboBoxStudTeacher.getSelectedItem()== "-")
     {
        JOptionPane.showMessageDialog(null, "Please Select your Title"); 
     }
    
       else if (ComboBoxStudTeacher.getSelectedItem()== "Student")  //FOR STUDENT LOGIN AUTHENTICATION + CATCHING ID
       {  
      try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            URL= "jdbc:sqlserver://localhost:1433;databasename=CourseManagement";
                   
            Connection Con=DriverManager.getConnection(URL,un,up);
            String  sqltxt_Authentication="SELECT * FROM TblStudent WHERE SUName = " + "'"+UserNameLogin+"'" + "and SPass = "+"'"+ Pass+"'" ;
            Stat= Con.createStatement(); 
            RS_Authentication=Stat.executeQuery(sqltxt_Authentication);
         
            if (ComboBoxStudTeacher.getSelectedItem()== "Student")
            {
                RS_Authentication=Stat.executeQuery(sqltxt_Authentication); 
            }

            if (!RS_Authentication.next())
           {
                JOptionPane.showMessageDialog(null, "Incorrect UserName or Password");
           }  
            else 
            { 
                Flag=1;
                name=UserNameLogin;
            }
            
            
           
             Con.close();
       }catch (ClassNotFoundException | SQLException ex){
            //   JOptionPane.showMessageDialog(null, "Sign Up Unsuccesfull"); 
               }
       finally{
        if (Flag==1)
              try{
                  Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                  URL= "jdbc:sqlserver://localhost:1433;databasename=CourseManagement";
                   
                  Connection Con=DriverManager.getConnection(URL,un,up);
                  String txt="SELECT * FROM TblStudent WHERE SUName='"+UserNameLogin+"'";
                  Stat=Con.createStatement();
                  RS_Authentication=Stat.executeQuery(txt);
                  RS_Authentication.next();
                  StudentHomePage.id=RS_Authentication.getInt(1);
              }catch(Exception ex)
              {
                  JOptionPane.showMessageDialog(null, ex.getMessage()); 
              }finally{
                StudentHomePage.main(null);
                this.dispose(); 
              }
        
        //Getting SID
          }
           
                       
           }
      else if (ComboBoxStudTeacher.getSelectedItem()== "Teacher") { //FOR TEACHER LOGIN AUTHENTICATION + OPTIONAL CATCHING ID
           
      try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            URL= "jdbc:sqlserver://localhost:1433;databasename=CourseManagement";
                   
            Connection Con=DriverManager.getConnection(URL,un,up);
            String  sqltxt_Authentication= " SELECT * FROM TblTeacher WHERE TUName = " + "'"+UserNameLogin+"'" + "and TPass = "+"'"+ Pass+"'"; 
            Stat= Con.createStatement(); 
            RS_Authentication=Stat.executeQuery(sqltxt_Authentication);

            if (!RS_Authentication.next())
           {
                JOptionPane.showMessageDialog(null, "Incorrect UserName or Password");
           }  
            else 
            { 
                Flag=1;
                name=UserNameLogin;
                   }

             Con.close();
       }catch (ClassNotFoundException | SQLException ex){
            //   JOptionPane.showMessageDialog(null, "Sign Up Unsuccesfull"); 
               }
       finally{
        if (Flag==1)
                try{
                  Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                  URL= "jdbc:sqlserver://localhost:1433;databasename=CourseManagement";
                   
                  Connection Con=DriverManager.getConnection(URL,un,up);
                  String txt="SELECT * FROM TblTeacher WHERE TUName='"+UserNameLogin+"'";
                  Stat=Con.createStatement();
                  RS_Authentication=Stat.executeQuery(txt);
                  RS_Authentication.next();
                  TeacherHomePage.id=RS_Authentication.getInt(1);
              }catch(Exception ex)
              {
                  JOptionPane.showMessageDialog(null, ex.getMessage()); 
              }finally{
                 TeacherHomePage.main(null);
                 this.dispose(); 
              } 
          }
      }  
    }//GEN-LAST:event_btnLogInActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
        SignUp1.main(null);
        this.dispose();
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void usernameTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextField4ActionPerformed

    private void btnSignUp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignUp2ActionPerformed

    private void btnLogIn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogIn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogIn2ActionPerformed

    private void ComboBoxStudTeacher2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxStudTeacher2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxStudTeacher2ActionPerformed

    private void btnLogIn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogIn1ActionPerformed
        // TODO add your handling code here:
        SignUp1.main(null);
        this.dispose();
    }//GEN-LAST:event_btnLogIn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn1().setVisible(true);
                   }
        });
        // DatabaseLogin.main(null);


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxStudTeacher;
    private javax.swing.JComboBox<String> ComboBoxStudTeacher2;
    private javax.swing.JTextField UserName_login;
    private javax.swing.JPasswordField UserPassword_login;
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnLogIn1;
    private javax.swing.JButton btnLogIn2;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JButton btnSignUp2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JLabel lblIAmA;
    private javax.swing.JLabel lblIAmA2;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPassword2;
    private javax.swing.JLabel lblRequired;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsername4;
    private javax.swing.JLabel lblUsername5;
    private javax.swing.JTextField usernameTextField4;
    private javax.swing.JTextField usernameTextField5;
    // End of variables declaration//GEN-END:variables
}
