/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalProject1;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Tadele
 */
public class OpenFile extends javax.swing.JFrame {
    

    /**
     * Creates new form OpenFile
     */
    static int cid;
    public OpenFile() {
        initComponents();
        GetFile();
        Toolkit toolkit= getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2 );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        fileComboBox = new javax.swing.JComboBox<>();
        lblFileChoice = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFile = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave);
        btnSave.setBounds(510, 220, 80, 30);

        fileComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(fileComboBox);
        fileComboBox.setBounds(310, 220, 190, 30);

        lblFileChoice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFileChoice.setForeground(new java.awt.Color(255, 255, 255));
        lblFileChoice.setText("File Choice");
        jPanel1.add(lblFileChoice);
        lblFileChoice.setBounds(220, 220, 65, 28);

        tblFile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "FileID", "File Name", "Instructor", "Date Added"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFile);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 816, 120);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalProject1/Space-PNG-HD.png"))); // NOI18N
        jLabel8.setText("jLabel7");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 840, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileComboBoxActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String un=Database.uname, up=Database.upass;
         JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
         int r = jfc.showSaveDialog(null);
         if (r == JFileChooser.APPROVE_OPTION) {
                Statement stat;
                ResultSet rs;
                String url;
                byte[] fileBytes;
                String query;
                String fileName=jfc.getSelectedFile().getAbsolutePath();
                try {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    url = "jdbc:sqlserver://localhost:1433;databaseName=courseManagement";
                    Connection con = DriverManager.getConnection(url, un, up);
                    query="Select FID,FPath,UPFile FROM Files WHERE FID="+Integer.valueOf(String.valueOf(fileComboBox.getSelectedItem()));
                    stat=con.createStatement();
                    rs=stat.executeQuery(query);
                    OutputStream targetFile;
                    if (rs.next()) {
                     fileBytes = rs.getBytes(3);
                     if(rs.getString(2).matches("%.pdf"))
                        targetFile=  new FileOutputStream(fileName+".pdf");
                     else
                         targetFile=  new FileOutputStream(fileName+".ppt");
                     targetFile.write(fileBytes);
                     targetFile.close();
            }
                     
                    JOptionPane.showMessageDialog(null, "SAVED!");
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null,ex.getMessage());
                    //jl2.setText("ERROR!");
                }
            } 

    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpenFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpenFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpenFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpenFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpenFile().setVisible(true);
            }
        });
    }
    
    private void GetFile(){
    Statement stat;
    ResultSet rs;
    String url;
    String un,up;
    un=Database.uname;
    up=Database.upass;
    try{
         Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
         url="jdbc:sqlserver://localhost:1433;databasename=courseManagement";
         Connection con = DriverManager.getConnection(url,un,up);
         stat=con.createStatement();
         String cmdtxt="SELECT FID,FName,TUName,UploadDate FROM Files WHERE CourseID="+cid;
         rs = stat.executeQuery(cmdtxt);
         tblFile.setModel(DbUtils.resultSetToTableModel(rs));
         rs = stat.executeQuery(cmdtxt);
         fileComboBox.removeAllItems();
         while(rs.next()){  
         fileComboBox.addItem(String.valueOf(rs.getInt(1)));
         }

         con.close();
     }catch (Exception ex){
         JOptionPane.showMessageDialog(null,ex.getMessage());
     }
     finally{

     }

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> fileComboBox;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFileChoice;
    private javax.swing.JTable tblFile;
    // End of variables declaration//GEN-END:variables
}
