/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalProject1;


import static finalProject1.AddFile.id;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Tadele
 */
public class OpenFileTeacher extends javax.swing.JFrame {

    /**
     * Creates new form OpenFileTeacher
     */
    static int cid;
    String un=Database.uname, up=Database.upass;
   
    public OpenFileTeacher() {
        initComponents();
        GetFile();
        Toolkit toolkit= getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2 );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        fileComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFiles = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        btnAdd.setText("Add..");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd);
        btnAdd.setBounds(310, 240, 80, 30);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete);
        btnDelete.setBounds(280, 160, 70, 30);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave);
        btnSave.setBounds(210, 160, 60, 30);

        jPanel1.add(fileComboBox);
        fileComboBox.setBounds(70, 160, 129, 29);

        tblFiles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "FileID", "FileName", "FileDesc"
            }
        ));
        jScrollPane1.setViewportView(tblFiles);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 30, 375, 120);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalProject1/Space-PNG-HD.png"))); // NOI18N
        jLabel8.setText("jLabel7");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 400, 290);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void GetFile(){
    Statement stat;
    ResultSet rs;
    String url;
    String un,up;
    un=Database.uname;
    up=Database.upass;
   
    try{
         Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
         url="jdbc:sqlserver://localhost:1433;databasename=courseManagement";
         Connection con = DriverManager.getConnection(url,un,up);
         stat=con.createStatement();
         String cmdtxt="SELECT FID,FName AS [File Name],TUName AS [Teacher's User Name],UploadDate FROM Files WHERE CourseID="+cid;
         rs = stat.executeQuery(cmdtxt);
         tblFiles.setModel(DbUtils.resultSetToTableModel(rs));
         rs = stat.executeQuery(cmdtxt);
         fileComboBox.removeAllItems();
         boolean exists;
         while(rs.next()){  
             exists = false;
             String item=String.valueOf(rs.getInt(1));
             for (int index = 0; index < fileComboBox.getItemCount() && !exists; index++) {
             if (item.equals(fileComboBox.getItemAt(index))) {
                exists = true;
             }
            
             }
              if(!exists)
                fileComboBox.addItem(item);
             }
         con.close();
    }catch (Exception ex){
         JOptionPane.showMessageDialog(null,ex.getMessage());
     }
     finally{

     }
}

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
         JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
         int r = jfc.showSaveDialog(null);
         if (r == JFileChooser.APPROVE_OPTION) {
                Statement stat;
                ResultSet rs;
                String url;
                byte[] fileBytes;
                String query;
                String fileName=jfc.getSelectedFile().getAbsolutePath();
                try {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    url = "jdbc:sqlserver://localhost:1433;databaseName=courseManagement";
                    Connection con = DriverManager.getConnection(url, un, up);
                    query="Select FID,FPath,UPFile FROM Files WHERE FID="+Integer.valueOf(String.valueOf(fileComboBox.getSelectedItem()));
                    stat=con.createStatement();
                    rs=stat.executeQuery(query);
                    OutputStream targetFile;
                    if (rs.next()) {
                     fileBytes = rs.getBytes(3);
                     if(rs.getString(2).matches("%.pdf"))
                        targetFile=  new FileOutputStream(fileName+".pdf");
                     else
                         targetFile=  new FileOutputStream(fileName+".ppt");
                     targetFile.write(fileBytes);
                     targetFile.close();
            }
                     
                    JOptionPane.showMessageDialog(null, "SAVED!");
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null,ex.getMessage());
                    //jl2.setText("ERROR!");
                }
            } 

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        AddFile.cid=cid;
        AddFile.main(null);
  
        this.dispose();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if(fileComboBox.getSelectedIndex()==-1)
        {
            JOptionPane.showMessageDialog(null, "No file selected");
        }
        else
        {
                  Statement stat;
    
    String url;
    String un,up;
    un=Database.uname;
    up=Database.upass;
    int chosenid=Integer.valueOf(String.valueOf(fileComboBox.getSelectedItem()));
    try{
         Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
         url="jdbc:sqlserver://localhost:1433;databasename=courseManagement";
         Connection con = DriverManager.getConnection(url,un,up);
         stat=con.createStatement();
         String cmdtxt="SELECT FID, Courses.CourseID, Courses.CourseName, Courses.Instructor "+
                        "FROM Files JOIN Courses ON Courses.CourseID=Files.CourseID WHERE FID="+chosenid;
         ResultSet rs=stat.executeQuery(cmdtxt);
         rs.next();
         int cid=rs.getInt(2);
         String cname=rs.getString(3);
         String tname=rs.getString(4);
         cmdtxt="SELECT TblStudent.SID, TblStudent.SUName FROM TakesCourses "+
                 "JOIN TblStudent ON TakesCourses.SID=TblStudent.SID WHERE CourseID="+cid;
         rs=stat.executeQuery(cmdtxt);
         while(rs.next()){
             Database.AddSNotification(rs.getInt(1),tname , "File Deleted from Course "+cname);
         }
         cmdtxt="DELETE FROM Files WHERE FID="+chosenid;
         stat.executeUpdate(cmdtxt);
         JOptionPane.showMessageDialog(null, "DELETED!");
         con.close();
    }catch (Exception ex){
         JOptionPane.showMessageDialog(null,ex.getMessage());
     }finally{
        GetFile();
    }

        }
  
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpenFileTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpenFileTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpenFileTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpenFileTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpenFileTeacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> fileComboBox;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFiles;
    // End of variables declaration//GEN-END:variables
}
