/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalProject1;

import java.awt.Dimension;
import javax.swing.*;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import net.proteanit.sql.DbUtils;


public class StudentHomePage extends javax.swing.JFrame {
String un=Database.uname, up=Database.upass;
  String Pass;  /**
     * Creates new form StudentHomePage
     */
  private byte[] picture;
  FileInputStream fis;
  String Filename=null;
  byte[] ProfilePicture=null;
  
    static int id;
    private DefaultListModel<String> ListModel= new DefaultListModel();
    public StudentHomePage() {
        initComponents();
        Getaccountdata();
        AddCourses();
        GetCourse();
        GetNotifications();
       Toolkit toolkit= getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2 );
        
    }
public void image(byte[] image)
{
    this.picture=image;
}
public byte[] getImage(){
    return picture;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        panelHome = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblFirstName2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        btnRegister = new javax.swing.JButton();
        btnUnregister = new javax.swing.JButton();
        lblAvailable = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listCourses = new javax.swing.JList<>();
        logo1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblAvailable2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblAvailable1 = new javax.swing.JLabel();
        lblAvailable3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panelMyCourses = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourse = new javax.swing.JTable();
        btnOpenCourse = new javax.swing.JButton();
        courseComboBox = new javax.swing.JComboBox<>();
        lblCourseChoice = new javax.swing.JLabel();
        lblMyCourses = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        panelAccount = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        btnSignOut = new javax.swing.JButton();
        FirstNameTextField = new javax.swing.JTextField();
        EmailTextField = new javax.swing.JTextField();
        LastNameTextField = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        btnEdit = new javax.swing.JButton();
        lblPassword = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        UsernameTextField = new javax.swing.JTextField();
        ImageButton = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        panelNotifications = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNotifications = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lblNotifications5 = new javax.swing.JLabel();
        lblNotifications6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabbedPane.setBackground(new java.awt.Color(0, 0, 51));
        tabbedPane.setForeground(new java.awt.Color(0, 0, 51));
        tabbedPane.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tabbedPane.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N

        jPanel9.setBackground(new java.awt.Color(0, 102, 204));
        jPanel9.setForeground(new java.awt.Color(0, 153, 255));
        jPanel9.setLayout(null);

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));
        jPanel11.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalProject1/47768.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel11.add(jLabel4);
        jLabel4.setBounds(0, 0, 130, 140);

        jPanel9.add(jPanel11);
        jPanel11.setBounds(30, 30, 130, 140);

        lblFirstName2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblFirstName2.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstName2.setText(LogIn1.name);
        jPanel9.add(lblFirstName2);
        lblFirstName2.setBounds(30, 170, 130, 30);
        jPanel9.add(jScrollPane4);
        jScrollPane4.setBounds(210, 30, 2, 2);

        btnRegister.setText("REGISTER");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel9.add(btnRegister);
        btnRegister.setBounds(460, 270, 100, 30);

        btnUnregister.setText("UNREGISTER");
        btnUnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnregisterActionPerformed(evt);
            }
        });
        jPanel9.add(btnUnregister);
        btnUnregister.setBounds(580, 270, 110, 30);

        lblAvailable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAvailable.setForeground(new java.awt.Color(255, 255, 255));
        lblAvailable.setText("AVAILABLE COURSES");
        jPanel9.add(lblAvailable);
        lblAvailable.setBounds(210, 10, 240, 30);
        jPanel9.add(jSeparator1);
        jSeparator1.setBounds(210, 40, 480, 20);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        listCourses.setBackground(new java.awt.Color(204, 204, 204));
        listCourses.setModel(ListModel);
        jScrollPane5.setViewportView(listCourses);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel9.add(jPanel2);
        jPanel2.setBounds(210, 50, 480, 200);

        logo1.setBackground(new java.awt.Color(255, 0, 0));
        logo1.setFont(new java.awt.Font("Starcruiser", 2, 36)); // NOI18N
        logo1.setForeground(new java.awt.Color(0, 0, 102));
        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalProject1/download (1).png"))); // NOI18N
        jPanel9.add(logo1);
        logo1.setBounds(640, 10, 270, 180);

        jPanel5.setLayout(null);

        lblAvailable2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAvailable2.setForeground(new java.awt.Color(153, 153, 153));
        lblAvailable2.setText("Registering for Courses helps us get access to a variety of course Files");
        jPanel5.add(lblAvailable2);
        lblAvailable2.setBounds(20, 0, 490, 30);

        jLabel16.setBackground(new java.awt.Color(255, 0, 0));
        jLabel16.setFont(new java.awt.Font("orange juice", 2, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 0, 0));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalProject1/bac4k.png"))); // NOI18N
        jLabel16.setText("BIRANA");
        jPanel5.add(jLabel16);
        jLabel16.setBounds(0, 0, 640, 30);

        jPanel9.add(jPanel5);
        jPanel5.setBounds(220, 400, 470, 30);

        lblAvailable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAvailable1.setForeground(new java.awt.Color(204, 204, 204));
        lblAvailable1.setText("About Us");
        lblAvailable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAvailable1MouseClicked(evt);
            }
        });
        jPanel9.add(lblAvailable1);
        lblAvailable1.setBounds(830, 390, 80, 20);

        lblAvailable3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAvailable3.setForeground(new java.awt.Color(204, 204, 204));
        lblAvailable3.setText("@2019 Birana");
        lblAvailable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAvailable3MouseClicked(evt);
            }
        });
        jPanel9.add(lblAvailable3);
        lblAvailable3.setBounds(810, 410, 90, 20);

        jLabel14.setBackground(new java.awt.Color(255, 0, 0));
        jLabel14.setFont(new java.awt.Font("orange juice", 2, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 0, 0));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalProject1/bac4k.png"))); // NOI18N
        jLabel14.setText("BIRANA");
        jPanel9.add(jLabel14);
        jLabel14.setBounds(170, 0, 750, 440);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalProject1/Space-PNG-HD.png"))); // NOI18N
        jPanel9.add(jLabel11);
        jLabel11.setBounds(0, 0, 910, 450);

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE)
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        tabbedPane.addTab("HOME", panelHome);

        jPanel4.setLayout(null);

        tblCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CourseID", "Course Name", "Instructor", "Last Added"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCourse.setPreferredSize(new java.awt.Dimension(300, 400));
        jScrollPane1.setViewportView(tblCourse);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 890, 190);

        btnOpenCourse.setText("Open");
        btnOpenCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenCourseActionPerformed(evt);
            }
        });
        jPanel4.add(btnOpenCourse);
        btnOpenCourse.setBounds(540, 280, 59, 30);

        courseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseComboBoxActionPerformed(evt);
            }
        });
        jPanel4.add(courseComboBox);
        courseComboBox.setBounds(370, 280, 161, 30);

        lblCourseChoice.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCourseChoice.setForeground(new java.awt.Color(255, 255, 255));
        lblCourseChoice.setText("COURSE CHOICE");
        jPanel4.add(lblCourseChoice);
        lblCourseChoice.setBounds(250, 280, 100, 30);

        lblMyCourses.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        lblMyCourses.setForeground(new java.awt.Color(255, 255, 255));
        lblMyCourses.setText("MY COURSES");
        jPanel4.add(lblMyCourses);
        lblMyCourses.setBounds(360, 20, 176, 24);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalProject1/Space-PNG-HD.png"))); // NOI18N
        jPanel4.add(jLabel13);
        jLabel13.setBounds(0, -50, 920, 500);

        javax.swing.GroupLayout panelMyCoursesLayout = new javax.swing.GroupLayout(panelMyCourses);
        panelMyCourses.setLayout(panelMyCoursesLayout);
        panelMyCoursesLayout.setHorizontalGroup(
            panelMyCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelMyCoursesLayout.setVerticalGroup(
            panelMyCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMyCoursesLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        tabbedPane.addTab("MY COURSES", panelMyCourses);

        panelAccount.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username");
        jPanel1.add(lblUsername);
        lblUsername.setBounds(20, 280, 80, 30);

        btnSignOut.setText("SIGN OUT");
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });
        jPanel1.add(btnSignOut);
        btnSignOut.setBounds(20, 370, 110, 30);

        FirstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(FirstNameTextField);
        FirstNameTextField.setBounds(100, 160, 160, 30);
        jPanel1.add(EmailTextField);
        EmailTextField.setBounds(100, 240, 160, 30);

        LastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(LastNameTextField);
        LastNameTextField.setBounds(100, 200, 160, 30);

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email");
        jPanel1.add(lblEmail);
        lblEmail.setBounds(20, 240, 80, 30);
        jPanel1.add(passwordField);
        passwordField.setBounds(100, 320, 160, 30);

        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit);
        btnEdit.setBounds(140, 370, 120, 30);

        lblPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password");
        jPanel1.add(lblPassword);
        lblPassword.setBounds(20, 320, 80, 30);

        lblFirstName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstName.setText("First Name");
        jPanel1.add(lblFirstName);
        lblFirstName.setBounds(20, 160, 80, 30);

        lblLastName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(255, 255, 255));
        lblLastName.setText("Last Name");
        jPanel1.add(lblLastName);
        lblLastName.setBounds(20, 200, 80, 30);

        UsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(UsernameTextField);
        UsernameTextField.setBounds(100, 280, 160, 30);

        ImageButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ImageButton.setText("UPLOAD PHOTO");
        ImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImageButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ImageButton);
        ImageButton.setBounds(150, 120, 110, 30);

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));
        jPanel12.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalProject1/47768.png"))); // NOI18N
        jLabel2.setText("jLabel4");
        jPanel12.add(jLabel2);
        jLabel2.setBounds(0, 0, 130, 130);

        jPanel1.add(jPanel12);
        jPanel12.setBounds(10, 20, 130, 130);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalProject1/Space-PNG-HD.png"))); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(-30, 0, 950, 440);

        javax.swing.GroupLayout panelAccountLayout = new javax.swing.GroupLayout(panelAccount);
        panelAccount.setLayout(panelAccountLayout);
        panelAccountLayout.setHorizontalGroup(
            panelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAccountLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 939, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelAccountLayout.setVerticalGroup(
            panelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAccountLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        tabbedPane.addTab("ACCOUNT", panelAccount);

        panelNotifications.setBackground(new java.awt.Color(255, 255, 255));
        panelNotifications.setForeground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setLayout(null);

        tblNotifications.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Date", "Notification"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblNotifications);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(10, 20, 890, 380);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalProject1/Space-PNG-HD.png"))); // NOI18N
        jPanel3.add(jLabel10);
        jLabel10.setBounds(-30, -20, 950, 460);

        javax.swing.GroupLayout panelNotificationsLayout = new javax.swing.GroupLayout(panelNotifications);
        panelNotifications.setLayout(panelNotificationsLayout);
        panelNotificationsLayout.setHorizontalGroup(
            panelNotificationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE)
        );
        panelNotificationsLayout.setVerticalGroup(
            panelNotificationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNotificationsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        tabbedPane.addTab("NOTIFICATIONS", panelNotifications);

        jPanel10.setBackground(new java.awt.Color(0, 102, 204));
        jPanel10.setForeground(new java.awt.Color(0, 153, 255));
        jPanel10.setLayout(null);

        lblNotifications5.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        lblNotifications5.setForeground(new java.awt.Color(255, 255, 255));
        lblNotifications5.setText(LogIn1.name);
        jPanel10.add(lblNotifications5);
        lblNotifications5.setBounds(440, 0, 240, 30);

        lblNotifications6.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        lblNotifications6.setForeground(new java.awt.Color(255, 255, 255));
        lblNotifications6.setText("Welcome");
        jPanel10.add(lblNotifications6);
        lblNotifications6.setBounds(320, 0, 230, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalProject1/Space-PNG-HD.png"))); // NOI18N
        jPanel10.add(jLabel9);
        jLabel9.setBounds(0, 0, 920, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabbedPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 919, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tabbedPane))
        );

        tabbedPane.getAccessibleContext().setAccessibleName("tabbedPane");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextFieldActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
int len = (int)Filename.length();  
      Statement Stat;
        String URL;
        ResultSet RS;
       // Statement Stat;
          char[] input = passwordField.getPassword();

        Pass=String.valueOf(input) ;     
                String Url;
       String query;
        PreparedStatement pstmt;
        /*
        char[] input = passwordField.getPassword();
        Pass=String.valueOf(input) ;
        if (UsernameTextField.getText().isEmpty()||  Pass.isEmpty())
        {
              JOptionPane.showMessageDialog(null, "UserName and Password Cannot be Empty"); 
        }
        else
        {
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            URL= "jdbc:sqlserver://localhost:1433;databasename=CourseManagement";

            Connection Con=DriverManager.getConnection(URL,un,up);
            String sqltxt="SELECT * FROM TblStudent";
            Stat= Con.createStatement();
            RS=Stat.executeQuery(sqltxt);
          
            sqltxt="UPDATE TblStudent SET\n"
                    + "FName= " + "'" +FirstNameTextField.getText()+ "'"
                    + ",Lname= " + "'" +LastNameTextField.getText()+ "'"
                    + ",Email = " + "'" +EmailTextField.getText()+ "'"
                    + ",SUName= " + "'" +UsernameTextField.getText()+ "'"
                    + ",SPass = " + "'" +Pass + "' " 
                //    + ",Picture = " + "'" +jLabel1.getIcon() +"'"
                    + "WHERE SID = " + id ; */
            

                   Statement stat;
                ResultSet rs;
                String url;
                
              //  String query;
               // PreparedStatement pstmt;
                try {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    url = "jdbc:sqlserver://localhost:1433;databaseName=courseManagement";
                    Connection con = DriverManager.getConnection(url, un, up);
                   
                    stat = con.createStatement();
                  //  String cmdtxt="SELECT * FROM TblStudent WHERE SID="+id;
                   // rs = stat.executeQuery(cmdtxt);
                   // rs.next();
                   
                    query = "UPDATE TblStudent SET FName = ? , Lname=? , Email =? , SUName=? , SPass=?,Picture =? WHERE SID =?";
                    //stat.execute(sqltxt);
                    pstmt = con.prepareStatement(query);
                    pstmt.setString(1, FirstNameTextField.getText());
                    pstmt.setString(2, LastNameTextField.getText());
                    pstmt.setString(3, EmailTextField.getText());
                    pstmt.setString(4, UsernameTextField.getText());
                    pstmt.setString(5, Pass); 
                    pstmt.setBytes(6, ProfilePicture);//setBinaryStream(6, fis, len); 
                    pstmt.setInt(7, id); 
                    pstmt.executeUpdate();
                    
                    pstmt.close();
                    fis.close();
                    con.close();   
                    
                    JOptionPane.showMessageDialog(null, " Account Updated ");
                    
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null,ex.getMessage());
                    //jl2.setText("ERROR!");
                } 
                   
       /*   Stat=Con.createStatement();
          Stat.execute(sqltxt);
          Con.close();

            JOptionPane.showMessageDialog(null, "Account Updated");


        }catch (ClassNotFoundException | SQLException ex){
            JOptionPane.showMessageDialog(null, "Error Saving");
        }
        finally{

        }
        }  */
    }//GEN-LAST:event_btnEditActionPerformed

    private void LastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameTextFieldActionPerformed

    private void FirstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameTextFieldActionPerformed

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        // TODO add your handling code here:
        LogIn1.main(null);
        this.dispose();
    }//GEN-LAST:event_btnSignOutActionPerformed

    private void courseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseComboBoxActionPerformed

    private void btnOpenCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenCourseActionPerformed
        // TODO add your handling code here:
        if(courseComboBox.getSelectedIndex()==-1)
        {
            JOptionPane.showMessageDialog(null, "No Course Selected");
        }
        else
        {
            OpenFile.cid=Integer.valueOf(String.valueOf(courseComboBox.getSelectedItem()));
            OpenFile.main(null);
        }
    }//GEN-LAST:event_btnOpenCourseActionPerformed

    private void ImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImageButtonActionPerformed
      JFileChooser chooser=new JFileChooser();
      chooser.showOpenDialog(null);
      File f= chooser.getSelectedFile();
      Filename=f.getAbsolutePath();
      ImageIcon imageIcon = new ImageIcon(new ImageIcon(Filename).getImage().getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(),Image.SCALE_SMOOTH));
      jLabel2.setIcon(imageIcon); 
      jLabel4.setIcon(imageIcon);
      try {
          File image= new File (Filename);
          FileInputStream fis= new FileInputStream(image);
          ByteArrayOutputStream bos = new ByteArrayOutputStream();
          byte[] buf= new byte[1024];
          for (int readNum;(readNum=fis.read(buf))!=-1;)
          {
              bos.write(buf,0,readNum);
          }
          ProfilePicture= bos.toByteArray();
      }
      catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
      }
    }//GEN-LAST:event_ImageButtonActionPerformed

    private void btnUnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnregisterActionPerformed
        // TODO add your handling code here:
        int[] arr=listCourses.getSelectedIndices();
         Statement stat;
        ResultSet rs;
        String url;
        try{
         Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
         url="jdbc:sqlserver://localhost:1433;databasename=courseManagement";
         Connection con = DriverManager.getConnection(url,un,up);
         stat=con.createStatement();
         boolean found=false;
         for(int i:arr)
         {
             String cmdtxt="SELECT CourseID, CourseName FROM Courses WHERE CourseName='"+ListModel.get(i)+"'";
             rs = stat.executeQuery(cmdtxt);
             rs.next();
             int cid=rs.getInt(1);
             String cname=rs.getString(2);
             cmdtxt="DELETE FROM TakesCourses WHERE SID="+id+" AND CourseID="+cid;
             if(stat.executeUpdate(cmdtxt)==0){
                 found=true;
                 JOptionPane.showMessageDialog(null,"YOU WERE NOT REGISTERED FOR COURSE "+cname);
             }
             else{
                cmdtxt="SELECT TID, TUName FROM Courses JOIN TblTeacher ON Courses.Instructor=TblTeacher.TUName WHERE Courses.CourseID="+cid;
                rs=stat.executeQuery(cmdtxt);
                rs.next();
                Database.AddTNotification(rs.getInt(1), "One student UNREGISTERED FOR COURSE");
             }
             
         }
         if(!found)
            JOptionPane.showMessageDialog(null,"UNREGISTERED!");
         con.close();
     }catch (Exception ex){
         JOptionPane.showMessageDialog(null,ex.getMessage());
         //JOptionPane.showMessageDialog(null,"YOU WERE NOT REGISTERED!");
     }finally{
            GetCourse();
        }

    }//GEN-LAST:event_btnUnregisterActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        int[] arr=listCourses.getSelectedIndices();
         Statement stat;
        ResultSet rs;
        String url;
        String cname="";
        try{
         Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
         url="jdbc:sqlserver://localhost:1433;databasename=courseManagement";
         Connection con = DriverManager.getConnection(url,un,up);
         stat=con.createStatement();        
         for(int i:arr)
         {
             String cmdtxt="SELECT CourseID, CourseName FROM Courses WHERE CourseName='"+ListModel.get(i)+"'";
             rs = stat.executeQuery(cmdtxt);
             rs.next();
             int cid=rs.getInt(1);
             cname=rs.getString(2);
             cmdtxt="INSERT INTO TakesCourses VALUES("+id+","+cid+")";
             stat.execute(cmdtxt);
             cmdtxt="SELECT TID, TUName FROM Courses JOIN TblTeacher ON Courses.Instructor=TblTeacher.TUName WHERE Courses.CourseID="+cid;
             rs=stat.executeQuery(cmdtxt);
             rs.next();
             Database.AddTNotification(rs.getInt(1), "One student REGISTERED FOR COURSE");
         }
         JOptionPane.showMessageDialog(null,"REGISTERED!");
         con.close();
     }catch (Exception ex){
         //JOptionPane.showMessageDialog(null,ex.getMessage());
         JOptionPane.showMessageDialog(null,"ALREADY REGISTERED FOR COURSE "+cname);
     }finally{
            GetCourse();
        }

    }//GEN-LAST:event_btnRegisterActionPerformed

    private void lblAvailable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAvailable1MouseClicked
       this.dispose();
        AboutUs.main(null);
      SignUp1.us=2;  
    }//GEN-LAST:event_lblAvailable1MouseClicked

    private void lblAvailable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAvailable3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAvailable3MouseClicked
    private void Getaccountdata()
{
     Statement Stat;
     String URL;
     ResultSet RS;
     char[] input = passwordField.getPassword();
     ByteArrayOutputStream bos = new ByteArrayOutputStream();
                
                  
                   
          Pass=String.valueOf(input) ;
      try{
          
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            URL= "jdbc:sqlserver://localhost:1433;databasename=CourseManagement";

            Connection Con=DriverManager.getConnection(URL,un,up);
            String sqltxt="SELECT * FROM TblStudent WHERE SID = " + id;
            Stat= Con.createStatement();
            RS=Stat.executeQuery(sqltxt);
               
if (RS.next())
{
                   byte[] filebytes= RS.getBytes("Picture");
                  // ByteArrayInputStream bis = new ByteArrayInputStream();
                    ByteArrayInputStream bis=new ByteArrayInputStream(filebytes);
                    
                   BufferedImage bImage= ImageIO.read(bis); 
                   //OutputStream targetfile= new 
                           
                   ProfilePicture= RS.getString("Picture").getBytes();
                   FirstNameTextField.setText(RS.getString("Fname"));
                   LastNameTextField.setText(RS.getString("Lname"));
                   EmailTextField.setText(RS.getString("Email"));
                   UsernameTextField.setText(RS.getString("SUName"));
                   passwordField.setText(RS.getString("SPass"));
                   jLabel4.setIcon(new ImageIcon(bImage)); 
                   jLabel2.setIcon(new ImageIcon(bImage)); 
                   
             Con.close();
}
       }catch (ClassNotFoundException | SQLException ex){
               JOptionPane.showMessageDialog(null, "Error getting Data"); 
               }catch (Exception ex){
                 // JOptionPane.showMessageDialog(null, ex); 
               }
      
       finally{
        
       }  
}
    private void GetCourse(){
    Statement stat;
    ResultSet rs;
    String url;
    un=Database.uname;
    up=Database.upass;
    try{
         Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
         url="jdbc:sqlserver://localhost:1433;databasename=courseManagement";
         Connection con = DriverManager.getConnection(url,un,up);
         stat=con.createStatement();
         String cmdtxt="SELECT Courses.CourseID, Courses.CourseName, Courses.Instructor "+
                       "FROM Courses JOIN TakesCourses ON Courses.CourseID=TakesCourses.CourseID "+
                       "WHERE TakesCourses.SID="+id;
         rs = stat.executeQuery(cmdtxt);
         tblCourse.setModel(DbUtils.resultSetToTableModel(rs));
         rs = stat.executeQuery(cmdtxt);
         courseComboBox.removeAllItems();
          boolean exists;
         while(rs.next()){  
             exists = false;
             String item=String.valueOf(rs.getInt(1));
             for (int index = 0; index < courseComboBox.getItemCount() && !exists; index++) {
             if (item.equals(courseComboBox.getItemAt(index))) {
                exists = true;
             }
            
               }
              if(!exists)
                courseComboBox.addItem(item);
         }
         
         
         con.close();
     }catch (Exception ex){
         JOptionPane.showMessageDialog(null,ex.getMessage());
     }
     finally{

     }

}
    private void GetNotifications(){
    Statement stat;
    ResultSet rs;
    String url;
        try{
         Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
         url="jdbc:sqlserver://localhost:1433;databasename=courseManagement";
         Connection con = DriverManager.getConnection(url,un,up);
         stat=con.createStatement();
         String cmdtxt="SELECT NDate AS Date, TUName AS [Teacher's User Name], Notification  FROM "+
                        "Notifications "+
                        "WHERE Notifications.SID="+id;
         rs = stat.executeQuery(cmdtxt);
         tblNotifications.setModel(DbUtils.resultSetToTableModel(rs));
         
         con.close();
     }catch (Exception ex){
         JOptionPane.showMessageDialog(null,ex.getMessage());
     }
     finally{

     }

    }

    private void AddCourses(){
        Statement stat;
    ResultSet rs;
    String url;
        try{
         Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
         url="jdbc:sqlserver://localhost:1433;databasename=courseManagement";
         Connection con = DriverManager.getConnection(url,un,up);
         stat=con.createStatement();
         String cmdtxt="SELECT CourseID,CourseName FROM Courses";
         rs = stat.executeQuery(cmdtxt);
         
              while(rs.next())
            {
                ListModel.addElement(rs.getString(2));
            
            }
             listCourses.setModel(ListModel);
                     
         
                  con.close();
     }catch (Exception ex){
         JOptionPane.showMessageDialog(null,ex.getMessage());
     }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JTextField FirstNameTextField;
    private javax.swing.JButton ImageButton;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnOpenCourse;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JButton btnUnregister;
    private javax.swing.JComboBox<String> courseComboBox;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAvailable;
    private javax.swing.JLabel lblAvailable1;
    private javax.swing.JLabel lblAvailable2;
    private javax.swing.JLabel lblAvailable3;
    private javax.swing.JLabel lblCourseChoice;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblFirstName2;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMyCourses;
    private javax.swing.JLabel lblNotifications5;
    private javax.swing.JLabel lblNotifications6;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JList<String> listCourses;
    private javax.swing.JLabel logo1;
    private javax.swing.JPanel panelAccount;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelMyCourses;
    private javax.swing.JPanel panelNotifications;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTable tblCourse;
    private javax.swing.JTable tblNotifications;
    // End of variables declaration//GEN-END:variables
}
