
package finalProject1;


import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


public class TeacherHomePage extends javax.swing.JFrame {
String un=Database.uname, up=Database.upass;
String Pass;
static int id;
FileInputStream fis;
String Filename=null;
  byte[] ProfilePicture=null;
    /**
     * Creates new form TeacherHomePage
     */
    public TeacherHomePage() {
        initComponents();
        Getaccountdata();
        GetCourse();
        GetNotifications();
        Toolkit toolkit= getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2 );
        
      //  lblAvailable1.setText(getTime());
                             }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        panelHome = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblNotifications7 = new javax.swing.JLabel();
        logo1 = new javax.swing.JLabel();
        lblAvailable1 = new javax.swing.JLabel();
        lblAvailable2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panelCourses = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        btnOpen = new javax.swing.JButton();
        courseComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourses = new javax.swing.JTable();
        lblCourses = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        panelAccount = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LastNameTextField = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        FirstNameTextField = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        UsernameTextField = new javax.swing.JTextField();
        EmailTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        btnSignOut = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ImageButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        panelNotification = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblNotifications = new javax.swing.JTable();
        lblNotifications1 = new javax.swing.JLabel();
        btnNotify = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lblNotifications5 = new javax.swing.JLabel();
        lblNotifications6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel9.setBackground(new java.awt.Color(0, 102, 204));
        jPanel9.setForeground(new java.awt.Color(0, 153, 255));
        jPanel9.setLayout(null);

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));
        jPanel11.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalProject1/47768.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel11.add(jLabel4);
        jLabel4.setBounds(0, -10, 130, 160);

        jPanel9.add(jPanel11);
        jPanel11.setBounds(30, 30, 130, 140);

        lblNotifications7.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        lblNotifications7.setForeground(new java.awt.Color(255, 255, 255));
        lblNotifications7.setText(LogIn1.name);
        jPanel9.add(lblNotifications7);
        lblNotifications7.setBounds(30, 170, 130, 30);

        logo1.setBackground(new java.awt.Color(255, 0, 0));
        logo1.setFont(new java.awt.Font("Starcruiser", 2, 36)); // NOI18N
        logo1.setForeground(new java.awt.Color(0, 0, 102));
        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalProject1/download (1).png"))); // NOI18N
        jPanel9.add(logo1);
        logo1.setBounds(360, 90, 350, 240);

        lblAvailable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAvailable1.setForeground(new java.awt.Color(204, 204, 204));
        lblAvailable1.setText("About US");
        lblAvailable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAvailable1MouseClicked(evt);
            }
        });
        jPanel9.add(lblAvailable1);
        lblAvailable1.setBounds(810, 390, 100, 20);

        lblAvailable2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAvailable2.setForeground(new java.awt.Color(204, 204, 204));
        lblAvailable2.setText("@ 2019 HiLCoE");
        lblAvailable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAvailable2MouseClicked(evt);
            }
        });
        jPanel9.add(lblAvailable2);
        lblAvailable2.setBounds(790, 410, 100, 20);

        jLabel15.setBackground(new java.awt.Color(255, 0, 0));
        jLabel15.setFont(new java.awt.Font("orange juice", 2, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 0, 0));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalProject1/bac4k.png"))); // NOI18N
        jLabel15.setText("BIRANA");
        jPanel9.add(jLabel15);
        jLabel15.setBounds(190, 0, 770, 510);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalProject1/Space-PNG-HD.png"))); // NOI18N
        jPanel9.add(jLabel11);
        jLabel11.setBounds(0, 0, 940, 470);

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );

        tabbedPane.addTab("HOME", panelHome);

        jPanel1.setLayout(null);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete);
        btnDelete.setBounds(580, 300, 80, 30);

        btnOpen.setText("Open");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });
        jPanel1.add(btnOpen);
        btnOpen.setBounds(490, 300, 80, 30);

        jPanel1.add(courseComboBox);
        courseComboBox.setBounds(340, 300, 100, 30);

        tblCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "CourseID", "CourseName"
            }
        ));
        jScrollPane1.setViewportView(tblCourses);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 890, 220);

        lblCourses.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        lblCourses.setForeground(new java.awt.Color(255, 255, 255));
        lblCourses.setText("COURSES");
        jPanel1.add(lblCourses);
        lblCourses.setBounds(410, 30, 128, 24);

        btnAdd.setText("Add..");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd);
        btnAdd.setBounds(809, 393, 90, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalProject1/Space-PNG-HD.png"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(0, 0, 960, 470);

        javax.swing.GroupLayout panelCoursesLayout = new javax.swing.GroupLayout(panelCourses);
        panelCourses.setLayout(panelCoursesLayout);
        panelCoursesLayout.setHorizontalGroup(
            panelCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
        );
        panelCoursesLayout.setVerticalGroup(
            panelCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCoursesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabbedPane.addTab("COURSES", panelCourses);

        jPanel2.setLayout(null);

        LastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(LastNameTextField);
        LastNameTextField.setBounds(110, 170, 170, 30);

        lblFirstName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstName.setText("First Name");
        jPanel2.add(lblFirstName);
        lblFirstName.setBounds(30, 170, 130, 25);

        lblLastName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(255, 255, 255));
        lblLastName.setText("Last Name");
        jPanel2.add(lblLastName);
        lblLastName.setBounds(30, 210, 130, 25);

        FirstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(FirstNameTextField);
        FirstNameTextField.setBounds(110, 210, 170, 30);

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email");
        jPanel2.add(lblEmail);
        lblEmail.setBounds(30, 250, 130, 25);

        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username");
        jPanel2.add(lblUsername);
        lblUsername.setBounds(30, 290, 130, 25);

        lblPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password");
        jPanel2.add(lblPassword);
        lblPassword.setBounds(30, 330, 130, 25);

        UsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(UsernameTextField);
        UsernameTextField.setBounds(110, 290, 170, 30);
        jPanel2.add(EmailTextField);
        EmailTextField.setBounds(110, 250, 170, 30);
        jPanel2.add(passwordField);
        passwordField.setBounds(110, 330, 170, 30);

        btnSignOut.setText("SIGN OUT");
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });
        jPanel2.add(btnSignOut);
        btnSignOut.setBounds(30, 370, 120, 30);

        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel2.add(btnEdit);
        btnEdit.setBounds(160, 370, 110, 30);

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));
        jPanel12.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalProject1/47768.png"))); // NOI18N
        jLabel2.setText("jLabel4");
        jPanel12.add(jLabel2);
        jLabel2.setBounds(0, 0, 130, 140);

        jPanel2.add(jPanel12);
        jPanel12.setBounds(30, 20, 130, 140);

        ImageButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ImageButton.setText("UPLOAD PHOTO");
        ImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImageButtonActionPerformed(evt);
            }
        });
        jPanel2.add(ImageButton);
        ImageButton.setBounds(170, 120, 110, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalProject1/Space-PNG-HD.png"))); // NOI18N
        jPanel2.add(jLabel13);
        jLabel13.setBounds(0, 0, 940, 490);

        javax.swing.GroupLayout panelAccountLayout = new javax.swing.GroupLayout(panelAccount);
        panelAccount.setLayout(panelAccountLayout);
        panelAccountLayout.setHorizontalGroup(
            panelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
        );
        panelAccountLayout.setVerticalGroup(
            panelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );

        tabbedPane.addTab("ACCOUNT", panelAccount);

        jPanel3.setLayout(null);

        tblNotifications.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Date", "Notification"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblNotifications);

        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(20, 80, 850, 280);

        lblNotifications1.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        lblNotifications1.setForeground(new java.awt.Color(255, 255, 255));
        lblNotifications1.setText("NOTIFICATIONS");
        jPanel3.add(lblNotifications1);
        lblNotifications1.setBounds(350, 40, 220, 24);

        btnNotify.setText("Notify...");
        btnNotify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotifyActionPerformed(evt);
            }
        });
        jPanel3.add(btnNotify);
        btnNotify.setBounds(750, 380, 120, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalProject1/Space-PNG-HD.png"))); // NOI18N
        jPanel3.add(jLabel14);
        jLabel14.setBounds(0, 0, 910, 450);

        javax.swing.GroupLayout panelNotificationLayout = new javax.swing.GroupLayout(panelNotification);
        panelNotification.setLayout(panelNotificationLayout);
        panelNotificationLayout.setHorizontalGroup(
            panelNotificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNotificationLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelNotificationLayout.setVerticalGroup(
            panelNotificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );

        tabbedPane.addTab("NOTIFICATIONS", panelNotification);

        jPanel10.setBackground(new java.awt.Color(0, 102, 204));
        jPanel10.setForeground(new java.awt.Color(0, 153, 255));
        jPanel10.setLayout(null);

        lblNotifications5.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        lblNotifications5.setForeground(new java.awt.Color(255, 255, 255));
        lblNotifications5.setText(LogIn1.name);
        jPanel10.add(lblNotifications5);
        lblNotifications5.setBounds(470, 0, 240, 30);

        lblNotifications6.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        lblNotifications6.setForeground(new java.awt.Color(255, 255, 255));
        lblNotifications6.setText("   WELCOME    ");
        jPanel10.add(lblNotifications6);
        lblNotifications6.setBounds(310, 0, 230, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalProject1/Space-PNG-HD.png"))); // NOI18N
        jPanel10.add(jLabel9);
        jLabel9.setBounds(0, 0, 930, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        // TODO add your handling code here:
         if(courseComboBox.getSelectedIndex()==-1)
        {
            JOptionPane.showMessageDialog(null, "No Course Selected");
        }
        else
        {
            OpenFileTeacher.cid=Integer.valueOf(String.valueOf(courseComboBox.getSelectedItem()));
            AddFile.id=id;
            OpenFileTeacher.main(null);
        }
        
    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    String title=JOptionPane.showInputDialog("Enter Course Name: ");
    Statement stat;
    ResultSet rs;
    String url;
        try{
         Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
         url="jdbc:sqlserver://localhost:1433;databasename=courseManagement";
         Connection con = DriverManager.getConnection(url,un,up);
         stat=con.createStatement();
         String cmdtxt="SELECT TID,TUName FROM TblTeacher WHERE TID="+id;
         rs = stat.executeQuery(cmdtxt);
         rs.next();
         String name=rs.getString(2);
         cmdtxt="INSERT INTO Courses VALUES ('"+title+"', '"+name+"')";
         int x=stat.executeUpdate(cmdtxt);
         GetCourse();     
         con.close();
     }catch (Exception ex){
         JOptionPane.showMessageDialog(null,ex.getMessage());
     }
        finally{
            GetCourse();
        }
                                      
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
         Statement stat;
    String url;
        try{
         Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
         url="jdbc:sqlserver://localhost:1433;databasename=courseManagement";
         Connection con = DriverManager.getConnection(url,un,up);
         stat=con.createStatement();
         String cmdtxt="DELETE FROM Courses WHERE CourseID="+Integer.parseInt(String.valueOf(courseComboBox.getSelectedItem()));
         stat.execute(cmdtxt);
         courseComboBox.removeItem(courseComboBox.getSelectedItem());
         con.close();
     }catch (Exception ex){
         JOptionPane.showMessageDialog(null,ex.getMessage());
     }
        finally{
            GetCourse();
        }
                                      
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void FirstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameTextFieldActionPerformed

    private void UsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextFieldActionPerformed

    private void LastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameTextFieldActionPerformed

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        // TODO add your handling code here:
        LogIn1.main(null);
        this.dispose();
    }//GEN-LAST:event_btnSignOutActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int len = (int)Filename.length();  
 
          char[] input = passwordField.getPassword();

        Pass=String.valueOf(input) ;     
                String Url;
       String query;
        PreparedStatement pstmt;
      
                   Statement stat;
                ResultSet rs;
                String url;
                
             
                try {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    url = "jdbc:sqlserver://localhost:1433;databaseName=courseManagement";
                    Connection con = DriverManager.getConnection(url, un, up);
                    stat = con.createStatement();
                    query = "UPDATE TblTeacher SET FName = ? , Lname=? , Email =? , TUName=? , TPass=?,Picture =? WHERE TID =?";
                    pstmt = con.prepareStatement(query);
                    pstmt.setString(1, FirstNameTextField.getText());
                    pstmt.setString(2, LastNameTextField.getText());
                    pstmt.setString(3, EmailTextField.getText());
                    pstmt.setString(4, UsernameTextField.getText());
                    pstmt.setString(5, Pass); 
                    pstmt.setBytes(6, ProfilePicture); 
                    pstmt.setInt(7, id); 
                    pstmt.executeUpdate();
                    
                    pstmt.close();
                    fis.close();
                    con.close();   
                    
                    JOptionPane.showMessageDialog(null, "Account Updated");
                    
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null,ex.getMessage());
                 
                } 

    }//GEN-LAST:event_btnEditActionPerformed

    private void ImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImageButtonActionPerformed
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f= chooser.getSelectedFile();
        Filename=f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(Filename).getImage().getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(),Image.SCALE_SMOOTH));
        jLabel2.setIcon(imageIcon);
        jLabel4.setIcon(imageIcon);
        try {
            File image= new File (Filename);
            FileInputStream fis= new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf= new byte[1024];
            for (int readNum;(readNum=fis.read(buf))!=-1;)
            {
                bos.write(buf,0,readNum);
            }
            ProfilePicture= bos.toByteArray();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_ImageButtonActionPerformed

    private void lblAvailable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAvailable1MouseClicked
       this.dispose();
      AboutUs.main(null);
      SignUp1.us=3; 
    }//GEN-LAST:event_lblAvailable1MouseClicked

    private void lblAvailable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAvailable2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAvailable2MouseClicked

    private void btnNotifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotifyActionPerformed
        // TODO add your handling code here:
        Notify.main(null);
    }//GEN-LAST:event_btnNotifyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherHomePage().setVisible(true);
            }
        });
    }
     private void GetNotifications(){
    Statement stat;
    ResultSet rs;
    String url;
        try{
         Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
         url="jdbc:sqlserver://localhost:1433;databasename=courseManagement";
         Connection con = DriverManager.getConnection(url,un,up);
         stat=con.createStatement();
         String cmdtxt="SELECT NDate AS Date, Notification  FROM "+
                        "TNotifications WHERE TID="+id;
         rs = stat.executeQuery(cmdtxt);
         tblNotifications.setModel(DbUtils.resultSetToTableModel(rs));
         
         con.close();
     }catch (Exception ex){
         JOptionPane.showMessageDialog(null,ex.getMessage());
     }
     finally{

     }

}
    private void GetCourse(){
    Statement stat;
    ResultSet rs;
    String url;

    try{
         Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
         url="jdbc:sqlserver://localhost:1433;databasename=courseManagement";
         Connection con = DriverManager.getConnection(url,un,up);
         stat=con.createStatement();
         String cmdtxt="SELECT Courses.CourseID, Courses.CourseName "+
                       "FROM Courses JOIN TblTeacher ON Courses.Instructor=TblTeacher.TUName "+
                       "WHERE TID="+id;
         rs = stat.executeQuery(cmdtxt);
         tblCourses.setModel(DbUtils.resultSetToTableModel(rs));
         rs = stat.executeQuery(cmdtxt);
         courseComboBox.removeAllItems();
         boolean exists;
         while(rs.next()){  
             exists = false;
             String item=String.valueOf(rs.getInt(1));
             for (int index = 0; index < courseComboBox.getItemCount() && !exists; index++) {
             if (item.equals(courseComboBox.getItemAt(index))) {
                exists = true;
             }
            
         }
              if(!exists)
                courseComboBox.addItem(item);
         }
         
         con.close();
     }catch (Exception ex){
         JOptionPane.showMessageDialog(null,ex.getMessage());
     }

    }
      private void Getaccountdata()
{
     Statement Stat;
     String URL;
     ResultSet RS;
     char[] input = passwordField.getPassword();
     ByteArrayOutputStream bos = new ByteArrayOutputStream();
                
                  
                   
          Pass=String.valueOf(input) ;
      try{
          
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            URL= "jdbc:sqlserver://localhost:1433;databasename=CourseManagement";

            Connection Con=DriverManager.getConnection(URL,un,up);
            String sqltxt="SELECT * FROM TblTeacher WHERE TID = " + id;
            Stat= Con.createStatement();
            RS=Stat.executeQuery(sqltxt);
               
if (RS.next())
{
                   byte[] filebytes= RS.getBytes("Picture");
                  // ByteArrayInputStream bis = new ByteArrayInputStream();
                    ByteArrayInputStream bis=new ByteArrayInputStream(filebytes);
                    
                   BufferedImage bImage= ImageIO.read(bis); 
                   //OutputStream targetfile= new 
                           
                   ProfilePicture= RS.getString("Picture").getBytes();
                   FirstNameTextField.setText(RS.getString("Fname"));
                   LastNameTextField.setText(RS.getString("Lname"));
                   EmailTextField.setText(RS.getString("Email"));
                   UsernameTextField.setText(RS.getString("TUName"));
                   passwordField.setText(RS.getString("TPass"));
                   jLabel4.setIcon(new ImageIcon(bImage)); 
                   jLabel2.setIcon(new ImageIcon(bImage)); 
                   
             Con.close();
}
       }catch (ClassNotFoundException | SQLException ex){
               JOptionPane.showMessageDialog(null, "Error getting Data"); 
               }catch (Exception ex){
             //  JOptionPane.showMessageDialog(null, ex); 
               }
      
       finally{
        
       }  
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JTextField FirstNameTextField;
    private javax.swing.JButton ImageButton;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNotify;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JComboBox<String> courseComboBox;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAvailable1;
    private javax.swing.JLabel lblAvailable2;
    private javax.swing.JLabel lblCourses;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblNotifications1;
    private javax.swing.JLabel lblNotifications5;
    private javax.swing.JLabel lblNotifications6;
    private javax.swing.JLabel lblNotifications7;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel logo1;
    private javax.swing.JPanel panelAccount;
    private javax.swing.JPanel panelCourses;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelNotification;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTable tblCourses;
    private javax.swing.JTable tblNotifications;
    // End of variables declaration//GEN-END:variables
}
